DryPhys: CMakeLists.txt File Reference
CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 3.12.0) project(DryPhys VERSION 1.0.0) option(phys_build_all "Builds all libraries
unit and code samples OFF option (phys_build_tests "Builds all libraries and unit tests." OFF) option(phys_build_samples "Builds all libraries and code samples." OFF) option(phys_configure_docs "Builds all libraries while configuring the Doxygen file for documentation generation." OFF) option(phys_enable_coverage "Builds all libraries
unit and code samples OFF unit and enables coverage options OFF option (phys_format_codebase "Builds all libraries while also formatting the code." OFF) option(phys_double_precision "Builds all libraries using double-precision floating point arithmetic enabled." OFF) option(phys_four_word_alignment "Builds all libraries while padding certain classes to make use of four-word alignment." OFF) if(phys_format_codebase AND NOT WIN32) execute_process(COMMAND bash cmake/scripts/format-codebase.sh WORKING_DIRECTORY $
OUTPUT_QUIET endif () if(phys_enable_coverage) set(phys_build_tests ON) set(CMAKE_BUILD_TYPE "Debug") set(CMAKE_CXX_FLAGS $
Variables
unit tests
Function Documentation
cmake_minimum_required()
cmake_minimum_required (VERSION 3.12. 0)
option() [1/2]
unit and code samples OFF option (phys_build_tests "Builds all libraries and unit tests." OFF)
References option().
Referenced by option(), and option().
option() [2/2]
unit and code samples OFF unit and enables coverage options OFF option (phys_format_codebase "Builds all libraries while also formatting the code." OFF)
References option().
endif()
coverage endif ()
References endif().
Referenced by endif().
Variable Documentation
tests
unit and code samples OFF unit tests