DryPhys: tests/testAllVector3DFunctions.cpp File Reference
testAllVector3DFunctions.cpp File Reference
#include <dryphys/vector3d.hpp>
#include <gtest/gtest.h>
Functions
GTEST_TEST (testVector3DFunctions, paddingIncreasesClassSizeByTheSizeOfOneAdditionalReal)
GTEST_TEST (testVector3DFunctions, differentConstructorsInitializeObjectsAsExpected)
GTEST_TEST (testVector3DFunctions, overloadedComparsionOperatorsPerformElementwiseComparisons)
GTEST_TEST (testVector3DFunctions, subscriptOperatorsCanReturnAndSetTheInternalData)
GTEST_TEST (testVector3DFunctions, overloadedArithmeticOperatorsActOnElementsOfTheVector)
GTEST_TEST (testVector3DFunctions, invertFunctionSwapsTheSignOfAllElements)
GTEST_TEST (testVector3DFunctions, magnitudeFunctionsCalculateTheLengthOfAVector)
GTEST_TEST (testVector3DFunctions, normalizeDividesTheElementsByTheMagnitude)
GTEST_TEST (testVector3DFunctions, vectorMultiplicationHasThreeUniqueForms)
GTEST_TEST (testVector3DFunctions, ourTupleLikeAPIProvidesReadAccessToTheElementsViaStructuredBindings)
GTEST_TEST (testVector3DFunctions, ourTupleLikeAPIProvidesWriteAccessToTheElementsViaStructuredBindings)
int main (int argc, char **argv)
Function Documentation
GTEST_TEST() [1/11]
GTEST_TEST (testVector3DFunctions , paddingIncreasesClassSizeByTheSizeOfOneAdditionalReal)
GTEST_TEST() [2/11]
GTEST_TEST (testVector3DFunctions , differentConstructorsInitializeObjectsAsExpected)
GTEST_TEST() [3/11]
GTEST_TEST (testVector3DFunctions , overloadedComparsionOperatorsPerformElementwiseComparisons)
GTEST_TEST() [4/11]
GTEST_TEST (testVector3DFunctions , subscriptOperatorsCanReturnAndSetTheInternalData)
GTEST_TEST() [5/11]
GTEST_TEST (testVector3DFunctions , overloadedArithmeticOperatorsActOnElementsOfTheVector)
GTEST_TEST() [6/11]
GTEST_TEST (testVector3DFunctions , invertFunctionSwapsTheSignOfAllElements)
References DryPhys::Vector3D::invert().
GTEST_TEST() [7/11]
GTEST_TEST (testVector3DFunctions , magnitudeFunctionsCalculateTheLengthOfAVector)
References DryPhys::Vector3D::magnitude().
GTEST_TEST() [8/11]
GTEST_TEST (testVector3DFunctions , normalizeDividesTheElementsByTheMagnitude)
References DryPhys::Vector3D::normalize().
GTEST_TEST() [9/11]
GTEST_TEST (testVector3DFunctions , vectorMultiplicationHasThreeUniqueForms)
GTEST_TEST() [10/11]
GTEST_TEST (testVector3DFunctions , ourTupleLikeAPIProvidesReadAccessToTheElementsViaStructuredBindings)
GTEST_TEST() [11/11]
GTEST_TEST (testVector3DFunctions , ourTupleLikeAPIProvidesWriteAccessToTheElementsViaStructuredBindings)
main()
int main (int argc, char ** argv)