name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  windows-builds:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Dphys_build_all=ON

      - name: Build
        run: cmake --build .

      - name: Install
        run: cmake --build . --target install

      - name: Test
        run: ctest --output-on-failure

  nix-builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Dphys_build_all=ON

      - name: Build
        run: cmake --build .

      - name: Install
        run: sudo cmake --build . --target install

      - name: Test
        run: ctest --output-on-failure
